randomising characters points
Alakind/NSU pull request #2
Opened 2022-09-20 07:09 UTC by Alakind

2022-09-25 06:31 UTC, Ningyo requested changes

2022-09-25 06:31 UTC, Ningyo commented on csharp/Program.cs
> +for (int i = 0; i < characters.Length; i++) {
если i нужен только для итерирования, можно использовать вместо for - foreach

2022-09-25 06:31 UTC, Ningyo commented on csharp/src/model/Character.cs
> +    public int Coolness
можно сделать сразу проперти с приватным сеттером. меньше места займёт и понятнее будет

2022-09-25 06:31 UTC, Ningyo commented on csharp/src/util/FileReader.cs
> +        for (int i = lines.Length - 1; i >= 1; i--)
переупорядочивание можно сделать короче. см OrderBy

2022-09-25 06:31 UTC, Ningyo commented on csharp/src/view/ConsoleView.cs
> +        Console.WriteLine(character.Name + ", " + character.Coolness.ToString());
здесь строк немного, так что можно использовать [интерполяцию строк](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) - будет красивее, понятнее, ToString можно не писать

2022-10-02 05:37 UTC, Ningyo requested changes

2022-10-02 05:37 UTC, Ningyo commented on csharp/src/model/Character.cs
> +    public int Coolness
вижу, что сделали проперти. в несколько строк их писать не обязательно, если внутри нет никакой логики

2022-10-02 05:37 UTC, Ningyo commented on csharp/src/util/FileReader.cs
> +        Character[] characters = new Character[lines.Length];
не очень очевидно, что здесь именно 100 претендентов. ни название файла об этом не говорит, ни переменные, ни комментарии

2022-10-02 05:37 UTC, Ningyo commented on csharp/src/util/FileReader.cs
> +class FileReader
не очень подходящее название для содержания. как будто должен просто читать из файла, а по сути - это генератор претендентов из формулировки задачи

2022-10-04 08:36 UTC, Ningyo requested changes

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Character.cs
> +
лишняя пустая строка

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Character.cs
> +    public int Coolness{ get; private set; }
лучше поля выносить наверх, потом все функции

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +
лишняя пустая строка

2022-10-04 08:36 UTC, Ningyo commented on csharp/Program.cs
> +// var character = hall.NextCharacter();
закомменченный код не нужен

2022-10-04 08:36 UTC, Ningyo commented on csharp/Program.cs
> +Character? groom = diana.ClassicSolution();
1. название функции должно быть глагольным
2. если вам нужно несколько алгоритмов, не нужно писать их несколькими функциями в одной принцессе. можете сделать несколько принцесс, например

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +
лишняя пустая строка

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
по условию подруга может сравнивать только претендентов, которых принцесса видела

2022-10-04 08:36 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +    public static bool CompareCharacters(Character? firstCharacter, Character? secondCharacter)
хотя бы саммари, или понятное название

2022-10-04 16:14 UTC, Ningyo requested changes

2022-10-04 16:14 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        if (CharactersInHall.Length == PassedNumber) {
как-то у вас странно скобки то на одной строке с кодом, то на отдельной. хорошо бы хотя бы однообразно делать

2022-10-04 16:14 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +
лишняя пустая строка

2022-10-04 16:14 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        while (GreatWaitingRoom.PassedNumber < 40)
magic numbers - хорошо бы вынести хотя бы в приватные константы (если они нигде больше не дублируются) или в отдельный класс с константами, если используются где-то ещё. у константы должно быть понятное имя и по возможности саммари

2022-10-04 16:14 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        Character? coolestYet = GreatWaitingRoom.NextCharacter();
если принцесса обращается с Character - то что ей мешает самой смотреть его coolness, кроме пары строк в формулировке задачи? тип претендента ей это вроде не запрещает?)

2022-10-04 16:14 UTC, Ningyo commented on csharp/src/view/ConsoleView.cs
> +        Console.WriteLine($"Princess have picked: {character.Name}!!! They are solid {character.Coolness}/100!!!");
функцию счастья забыли. по условию, должно быть 10, если никого не выбрала, 0 - до 50 и coolness от 51 до 100

2022-10-11 08:32 UTC, Ningyo requested changes

2022-10-11 08:32 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +    public int countHappines(Character? groom) {
PascalCase

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +    public Hall GreatWaitingRoom { get; private set; }
private readonly. зачем ему быть публичным?

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        this.CharactersBeen = new List<Character>();
странное название. я не понимаю, по какому правилу английского языка вы назвали. плюс, это не согласуется с вашим PassedNumber. тут у вас Passed, там Been...

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +            CharactersBeen.Add(CurrentCharacter);
у вас функция называется "следующий претендент" (что тоже в общем-то не очень правильно - это не глагол). а внутри вы добавляете его в список посещённых. это не то, чего ожидаешь от функции, всем своим видом говорящей "я верну тебе следующего претендента"

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        for (int i = 0; i < CharactersBeen.Count; i++)
незачем руками перебирать список. воспользуйтесь какой-нибудь стандартной функцией

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +            else if (CurrentCharacter?.Name == name)
вы проходитесь по списку, и каждый раз сравниваете, не равно ли имя из параметра имени текущего претендента. который, очевидно, в единственном числе у вас присутствует. вас ничего не смущает?

2022-10-12 17:20 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
всё ещё не вижу проверки. вы там добавили обнуляемых значений, но сути не изменили. даже если у вас нет претендента в списке, текущая логика попытается сравнить null с чем-нибудь ещё, и получит какой-нибудь результат. вместо того, чтобы дать по рукам тому, кто с недопустимыми параметрами функцию вызывает.

2022-10-12 17:22 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +    public string? PickCoolest(string? currentCharacter, string? beenCharacter)
currentCharacter - звучит как претендент, а не его имя. хотя по типу вы явно имя передаёте

2022-10-12 17:22 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +    public static bool CompareCharacters(Character? firstCharacter, Character? secondCharacter)
у вас нигде нет саммари. это плохо. писать саммари - хорошая и полезная привычка

2022-10-12 17:28 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        CharactersPassed = 1;
почему здесь сразу 1? вы её только создали, она ещё ничего не сделала, а один уже прошёл?

2022-10-12 17:28 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        currentCharacter = Victoria.NextCharacter();
почему у вас подруга даёт следующего претендента? это обязанность холла

2022-10-12 17:28 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        Character? coolestYet = GreatWaitingRoom.NextCharacter();
всё то же самое. в алгоритме вы заменили на имя претендента. а в счастье оставили доступ к Coolness. принцесса имеет доступ к Coolness - зачем ей вся эта сложность с алгоритмом? если бы вы хотели от другой команды решить эту задачу, стали бы вы давать им как разработчик холла, например, такого претендента, у которого все поля для принцессы доступны, и надеяться, что они честно напишут алгоритм, а не посмотрят в Coolness?

2022-10-13 03:49 UTC, Alakind commented on csharp/src/model/Hall.cs
> +            CharactersBeen.Add(CurrentCharacter);
Но так она возвращает следующего персонажа. А поскольку она его возвращает, значит он теперь был у принцессы и доступен для сравнения.

2022-10-13 03:59 UTC, Alakind commented on csharp/src/model/Princess.cs
> +        currentCharacter = Victoria.NextCharacter();
Потому что через Холл можно сравнивать претендентов, а этим может заниматься только подруга. Принцесса сидит в тронном зале, а подруга заводит ей претендентов

2022-10-13 07:13 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
вопрос актуален

2022-10-13 07:17 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +            CharactersBeen.Add(CurrentCharacter);
значит, назовите так, чтобы было понятно, что ваш следующий претендент сразу считается посещённым. только без and. пожалуйста

2022-10-13 07:19 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +    public List<Character> CharactersInHall { get; private set; }
почему у вас эти списки публичные? кто извне холла сюда может что-то записать?

2022-10-13 07:19 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +    public int PassedNumber;
почему кол-во публичное? кто угодно его может перезаписать

2022-10-13 07:19 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        for (int i = 0; i < CharactersBeen.Count; i++)
вопрос актуален

2022-10-13 07:22 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        currentCharacter = Victoria.NextCharacter();
"Претенденты толпятся в прихожей (Hall), и входят к принцессе по очереди, по одному, причём их порядок определён случайным образом, т.е. вероятность появления какого-то претендента первым, или вторым, или сотым совершенно одинакова."
"Подруга  - девушка общительная, она знает всех знает всех претендентов, и также, также тусит с ними в прихожей. Принцесса может позвать свою подругу, и спросить кто лучше тот или этот, и она ответит абсолютно объективно. Но подруга немного “себе на уме”, поэтому ответ даст даст ответ только в том случае, если оба претендента уже побывали у принцессы."

не вижу, где бы здесь было сказано, что претендентов приводит подруга. а как можно сделать запрос всех претендентов "невидимым" для принцессы?

2022-10-13 07:23 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        Character? coolestYet = GreatWaitingRoom.NextCharacter();
теперь вы создали другую проблему. почему счастье считает холл? чья это ответственность понять, насколько счастлива принцесса?

2022-10-13 09:48 UTC, Alakind commented on csharp/src/model/Princess.cs
> +        currentCharacter = Victoria.NextCharacter();
Добавил тронный зал, через который принцесса зовёт претендентов

2022-10-13 09:48 UTC, Alakind commented on csharp/src/model/Hall.cs
> +    public List<Character> CharactersInHall { get; private set; }
Поправил

2022-10-13 09:48 UTC, Alakind commented on csharp/src/model/Hall.cs
> +    public int PassedNumber;
Поправил

2022-10-13 09:48 UTC, Alakind commented on csharp/src/model/Friend.cs
> +    public string? PickCoolest(string? currentCharacter, string? beenCharacter)
Поправил

2022-10-13 09:49 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        for (int i = 0; i < CharactersBeen.Count; i++)
Вроде поменял уже

2022-10-13 09:50 UTC, Alakind commented on csharp/src/model/Hall.cs
> +            CharactersBeen.Add(CurrentCharacter);
Поменял passed и been на visited, чтобы очевидно было, что текущий считается

2022-10-13 09:50 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        this.CharactersBeen = new List<Character>();
Поправил

2022-10-13 09:50 UTC, Alakind commented on csharp/src/model/Princess.cs
> +        Character? coolestYet = GreatWaitingRoom.NextCharacter();
Поправил

2022-10-13 09:50 UTC, Alakind commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
поправил

2022-10-18 07:37 UTC, Alakind commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
Выкидывать ошибку

2022-10-18 07:42 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        return (int) coolness;
вместо if (coolness == null) можно спросить !coolness.HasValue
coolness.Value

2022-10-18 07:42 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        for (int i = 0; i < CharactersBeen.Count; i++)
FirstOrDefault какой-нибудь посмотрите

2022-10-18 07:47 UTC, Ningyo requested changes

2022-10-18 07:47 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +            beenCharacterName == null ||
тут остался been

2022-10-18 07:47 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +    public Character? GetBeenCharacterByName(string? name)
тоже been остался

2022-10-18 07:57 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        for (int i = 0; i < CharactersBeen.Count; i++)
Поправил

2022-10-18 08:18 UTC, Alakind commented on csharp/src/model/Friend.cs
> +        if (firstCharacter == null || secondCharacter == null) {
Поправил

2022-10-18 08:19 UTC, Alakind commented on csharp/src/model/Princess.cs
> +        return (int) coolness;
Поправил

2022-10-18 08:20 UTC, Alakind commented on csharp/src/model/Friend.cs
> +            beenCharacterName == null ||
Поправил

2022-10-18 08:20 UTC, Alakind commented on csharp/src/model/Hall.cs
> +    public Character? GetBeenCharacterByName(string? name)
Поправил

2022-10-23 07:23 UTC, Ningyo requested changes

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        if (CurrentCharacter?.Name == name)
что будет, если
а. CurrentCharacter == null и name == null
б. CurrentCharacter.Name == null и name == null
? зачем вы вообще указываете, что аргумент name может быть null?

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        if (foundCharacter != null) {
скобки скачут, то на одной строке, то на разных. неаккуратно

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +    public string? PickCoolest(string? currentCharacterName, string? visitedCharacterName)
зачем вы говорите, что можно вернуть null и принять null как аргумент? разве может имя быть null? после добавления прокидывания ошибки у вас саммари и контракт функции больше не совпадают с фактическим поведением

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +            GreatWaitingRoom.GetVisitedCharacterByName(currentCharacterName)?.Coolness
если здесь вы уже уверенны, что претендент в списке точно есть, потому что проверили это выше, хоть даже отдельным вызовом, то зачем вносить смуту и делать вид, будто бы ...?.Coolness может быть null? это вызывает вопросы, не появился ли логической ошибки, если у вас здесь будет сравнение null'ов

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +        if (
этот иф можно переделать в тернарное выражение

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        // TODO: ternary
жду реализации этого туду)

2022-10-23 07:23 UTC, Ningyo commented on csharp/src/model/Princess.cs
> +        else if (coolness < Constants.NumberOfCharacters / 2)
т.к. у вас внутри предыдущего блока стоит return,  **else** if делать не обязательно. можно просто if, т.к. вы в любом случае сюда попадёте, если HasValue

2022-10-23 14:26 UTC, Alakind commented on csharp/src/model/Friend.cs
> +            GreatWaitingRoom.GetVisitedCharacterByName(currentCharacterName)?.Coolness
Да, но без ? IDE всё равно пишет "Dereference of a possibly null reference." Как этого избежать?

2022-10-23 14:29 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        // TODO: ternary
Сделал

2022-10-23 14:29 UTC, Alakind commented on csharp/src/model/Princess.cs
> +        else if (coolness < Constants.NumberOfCharacters / 2)
Сделал

2022-10-23 14:29 UTC, Alakind commented on csharp/src/model/Friend.cs
> +        if (
Сделал

2022-10-23 14:30 UTC, Alakind commented on csharp/src/model/Friend.cs
> +    public string? PickCoolest(string? currentCharacterName, string? visitedCharacterName)
Сделал везде более прозрачную логику с этими null

2022-10-23 14:30 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        if (foundCharacter != null) {
Поправил

2022-10-23 14:30 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        if (CurrentCharacter?.Name == name)
Переделал всю логику с null-ами

2022-10-25 08:54 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +            GreatWaitingRoom.GetVisitedCharacterByName(currentCharacterName)?.Coolness
попробуйте resharper - он много всякого подсказывает, в т.ч. какой специальный комментарий можно оставить, чтобы ide успокоилась

2022-10-25 08:56 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        // TODO: ternary
можно упростить)

2022-10-25 08:58 UTC, Ningyo requested changes

2022-10-25 08:58 UTC, Ningyo commented on csharp/src/model/Friend.cs
> +        return  GreatWaitingRoom.GetVisitedCharacterByName(currentCharacterName).Coolness
1. два пробела
2.можно создать несколько доп. переменных и сократить строку. читать сравнение, разнесённое на несколько строк, очень неудобно)

2022-10-25 09:34 UTC, Alakind commented on csharp/src/model/Hall.cs
> +        if (CurrentCharacter?.Name == name)
Аргумент name не может быть null, всё правильно

2022-10-26 13:52 UTC, Ningyo commented on csharp/src/model/Hall.cs
> +        if (CurrentCharacter?.Name == name)
ну вообще ничего не запрещает ни создать претендента с null именем, ни спросить холл GetVisitedCharacterByName по name == null, т.к. null - валидное значение для строки. но оке

2022-10-26 13:57 UTC, Ningyo approved these changes

2022-10-26 13:57 UTC, merged