Csharp dev
Alakind/NSU pull request #4
Opened 2022-12-20 08:49 UTC by Alakind

2022-12-20 09:02 UTC, Ningyo requested changes

2022-12-20 09:02 UTC, Ningyo commented on csharp/PickyPrincessTest/FriendTest.cs
> +        var characterName1 = hall.GetNextVisitorName();
лучше по смыслу назвать, не первый второй, а какой-нибудь лучший-худший

2022-12-20 09:02 UTC, Ningyo commented on csharp/PickyPrincessTest/FriendTest.cs
> +        var hall = new Hall(generator);
можно замокать холл и\или генератор, чтобы управлять отсюда списком претендентов, и не гадать, какой из них лучше var coolestCharacter = ... а явно это указать

2022-12-20 09:02 UTC, Ningyo commented on csharp/PickyPrincessTest/FriendTest.cs
> +        Assert.ThrowsException<InvalidInputException>(action);
если есть текст ошибки, можно текст проверить на всякий случай

2022-12-20 09:02 UTC, Ningyo commented on csharp/PickyPrincessTest/HallTest.cs
> +    public void NextCharacterTest()
проверить, что если есть претенденты, возвращается какой-то не null и не ошибка: доп. можно проверить, что вы в генераторе отдали в таком-то порядке претендентов, холл их в таком же отдал. (здесь не обязательно 100, можете на 2 или 3 проверить)

2022-12-20 09:02 UTC, Ningyo commented on csharp/PickyPrincessTest/PrincessTest.cs
> +        Assert.AreEqual(0, princess.GetHappines(character.Coolness));
в NUnit есть [Case], тут тоже должно быть что-то похожее. это по сути кейсы

2022-12-21 14:15 UTC, Ningyo commented
всякие bin\obj\debug заигнорьте, пожалуйста. очень пугает такое кол-во файлов в пулл реквесте

2022-12-21 14:20 UTC, Ningyo requested changes

2022-12-21 14:20 UTC, Ningyo commented on csharp/PickyPrincessTest/UnitTest1.cs
> +    public void NamesUniq()
Uniq**ue**

2022-12-21 14:20 UTC, Ningyo commented on csharp/PickyPrincessTest/UnitTest1.cs
> +public class UnitTest1
название класса не очень говорящее

2022-12-21 14:20 UTC, Ningyo commented on csharp/PickyPrincessTest/UnitTest1.cs
> +        for (int i = 0; i < characters.Length; i++) {
не очень понимаю, что вы тут делаете с велосипедом. в fluent assertions есть метод для проверки, что список содержит только уникальные значения, если вы это хотели)

2022-12-21 14:20 UTC, Ningyo commented on csharp/pickeprincess/src/model/Hall.cs
> +        if (CharactersVisited.Count == 100)
magic. если используется ещё где-то в программе, можете сделать класс с константами для всех, или добавить в appsettings. иначе хотя бы локальную константу

2022-12-21 14:20 UTC, Ningyo commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +        string[] lines = System.IO.File.ReadAllLines(Path.Combine(Environment.CurrentDirectory, $@"res", "top100characters.txt"));
зачем $@ добавили?)

2022-12-21 14:20 UTC, Ningyo commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +    public Character[] GetCharactersMock()
если это мок - ему место рядом с тестами, а не в классе настоящей логики

2022-12-21 14:20 UTC, Ningyo commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +        string[] lines = {
это можно было в for каком-нибудь нагенерить

2022-12-22 10:02 UTC, Alakind commented on csharp/PickyPrincessTest/FriendTest.cs
> +        Assert.ThrowsException<InvalidInputException>(action);
Сделал

2022-12-22 10:03 UTC, Alakind commented on csharp/PickyPrincessTest/UnitTest1.cs
> +    public void NamesUniq()
Поправил

2022-12-22 10:03 UTC, Alakind commented on csharp/PickyPrincessTest/UnitTest1.cs
> +public class UnitTest1
Поправил

2022-12-22 10:06 UTC, Alakind commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +        string[] lines = System.IO.File.ReadAllLines(Path.Combine(Environment.CurrentDirectory, $@"res", "top100characters.txt"));
Это я эксперементировал с относительными путями. Поправил

2022-12-22 11:11 UTC, Alakind commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +    public Character[] GetCharactersMock()
Поправил

2022-12-22 11:14 UTC, Alakind commented on csharp/pickeprincess/src/util/CharacterGenerator.cs
> +        string[] lines = {
Поправил

2022-12-22 11:15 UTC, Alakind commented on csharp/pickeprincess/src/model/Hall.cs
> +        if (CharactersVisited.Count == 100)
Поправил

2022-12-22 11:31 UTC, Alakind commented on csharp/PickyPrincessTest/PrincessTest.cs
> +        Assert.AreEqual(0, princess.GetHappines(character.Coolness));
Поправил

2022-12-22 13:30 UTC, Alakind commented on csharp/PickyPrincessTest/HallTest.cs
> +    public void NextCharacterTest()
Поправил

2022-12-22 13:32 UTC, Alakind commented on csharp/PickyPrincessTest/HallTest.cs
> +    public void NextCharacterTest()
Поправил

2022-12-22 13:33 UTC, Alakind commented on csharp/PickyPrincessTest/FriendTest.cs
> +        var hall = new Hall(generator);
Сделал

2022-12-22 13:34 UTC, Alakind commented on csharp/PickyPrincessTest/FriendTest.cs
> +        var characterName1 = hall.GetNextVisitorName();
Дело сделано

2022-12-22 13:48 UTC, Alakind commented on csharp/PickyPrincessTest/UnitTest1.cs
> +        for (int i = 0; i < characters.Length; i++) {
Разобрался!

2022-12-25 07:26 UTC, Ningyo requested changes

2022-12-25 07:26 UTC, Ningyo commented on csharp/PickyPrincessTest/HallTest.cs
> +
лишние пустые строки(

2022-12-25 07:26 UTC, Ningyo commented on csharp/pickeprincess/.gitignore
> +bin/
к папке .net6.0 тоже вопросики есть - нужно ли оно действительно в гите или нет

2022-12-25 09:38 UTC, Alakind commented on csharp/PickyPrincessTest/HallTest.cs
> +
Поправил!

2022-12-25 09:38 UTC, Alakind commented on csharp/pickeprincess/.gitignore
> +bin/
Действительно не нужна, убрал

2022-12-26 13:19 UTC, merged